-- Complete setup script for all 26 Census views (county-level + state-level)
-- Co-authored with CoCo

-- Prerequisites:
-- 1. SafeGraph US Open Census Data marketplace listing installed
-- 2. Run as ACCOUNTADMIN or role with CREATE DATABASE/VIEW privileges
-- NOTE: Source table columns are mixed-case and must be double-quoted.

CREATE DATABASE IF NOT EXISTS CENSUS_AGENT;
USE DATABASE CENSUS_AGENT;
CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;

-- ============================================================
-- COUNTY-LEVEL VIEWS (one row per county)
-- ============================================================

------------------------------------------------------------
-- 1. V_POPULATION: Demographics by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_POPULATION AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
combined AS (
    SELECT
        LEFT(p.CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS,
        SUBSTR(p.CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        p."B01001e1" AS TOTAL_POPULATION,
        p."B01001e2" AS MALE_POPULATION,
        p."B01001e26" AS FEMALE_POPULATION,
        (p."B01001e3" + p."B01001e4" + p."B01001e5" + p."B01001e6" + COALESCE(p."B01001e27",0) + COALESCE(p."B01001e28",0) + COALESCE(p."B01001e29",0) + COALESCE(p."B01001e30",0)) AS POP_UNDER_18,
        (p."B01001e7" + p."B01001e8" + p."B01001e9" + p."B01001e10" + p."B01001e11" + p."B01001e12" + COALESCE(p."B01001e31",0) + COALESCE(p."B01001e32",0) + COALESCE(p."B01001e33",0) + COALESCE(p."B01001e34",0) + COALESCE(p."B01001e35",0) + COALESCE(p."B01001e36",0)) AS POP_18_TO_34,
        (p."B01001e13" + p."B01001e14" + p."B01001e15" + p."B01001e16" + p."B01001e17" + COALESCE(p."B01001e37",0) + COALESCE(p."B01001e38",0) + COALESCE(p."B01001e39",0) + COALESCE(p."B01001e40",0) + COALESCE(p."B01001e41",0)) AS POP_35_TO_54,
        (p."B01001e18" + p."B01001e19" + p."B01001e20" + p."B01001e21" + COALESCE(p."B01001e42",0) + COALESCE(p."B01001e43",0) + COALESCE(p."B01001e44",0) + COALESCE(p."B01001e45",0)) AS POP_55_TO_69,
        (p."B01001e22" + p."B01001e23" + p."B01001e24" + p."B01001e25" + COALESCE(p."B01001e46",0) + COALESCE(p."B01001e47",0) + COALESCE(p."B01001e48",0) + COALESCE(p."B01001e49",0)) AS POP_70_PLUS,
        r."B03002e3" AS WHITE_NON_HISPANIC,
        r."B03002e4" AS BLACK_NON_HISPANIC,
        r."B03002e5" AS NATIVE_AMERICAN_NON_HISPANIC,
        r."B03002e6" AS ASIAN_NON_HISPANIC,
        r."B03002e7" AS PACIFIC_ISLANDER_NON_HISPANIC,
        r."B03002e12" AS HISPANIC_LATINO
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B01" p
    LEFT JOIN US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B03" r
        ON p.CENSUS_BLOCK_GROUP = r.CENSUS_BLOCK_GROUP
)
SELECT
    f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(c.TOTAL_POPULATION) AS TOTAL_POPULATION,
    SUM(c.MALE_POPULATION) AS MALE_POPULATION,
    SUM(c.FEMALE_POPULATION) AS FEMALE_POPULATION,
    SUM(c.POP_UNDER_18) AS POP_UNDER_18,
    SUM(c.POP_18_TO_34) AS POP_18_TO_34,
    SUM(c.POP_35_TO_54) AS POP_35_TO_54,
    SUM(c.POP_55_TO_69) AS POP_55_TO_69,
    SUM(c.POP_70_PLUS) AS POP_70_PLUS,
    SUM(c.WHITE_NON_HISPANIC) AS WHITE_NON_HISPANIC,
    SUM(c.BLACK_NON_HISPANIC) AS BLACK_NON_HISPANIC,
    SUM(c.NATIVE_AMERICAN_NON_HISPANIC) AS NATIVE_AMERICAN_NON_HISPANIC,
    SUM(c.ASIAN_NON_HISPANIC) AS ASIAN_NON_HISPANIC,
    SUM(c.PACIFIC_ISLANDER_NON_HISPANIC) AS PACIFIC_ISLANDER_NON_HISPANIC,
    SUM(c.HISPANIC_LATINO) AS HISPANIC_LATINO
FROM combined c
JOIN fips f ON c.STATE_FIPS = f.STATE_FIPS AND c.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 2. V_INCOME: Household income by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_INCOME AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
income_dist AS (
    SELECT
        LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS,
        SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B19001e1" AS TOTAL_HOUSEHOLDS,
        "B19001e2" AS HH_UNDER_10K,
        ("B19001e3" + "B19001e4" + "B19001e5") AS HH_10K_TO_24K,
        ("B19001e6" + "B19001e7" + "B19001e8" + "B19001e9" + "B19001e10") AS HH_25K_TO_49K,
        ("B19001e11" + "B19001e12" + "B19001e13") AS HH_50K_TO_99K,
        ("B19001e14" + "B19001e15" + "B19001e16") AS HH_100K_TO_199K,
        "B19001e17" AS HH_200K_PLUS,
        "B19013e1" AS MEDIAN_HOUSEHOLD_INCOME,
        "B19301e1" AS PER_CAPITA_INCOME
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B19"
)
SELECT
    f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(d.TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS,
    SUM(d.HH_UNDER_10K) AS HH_UNDER_10K,
    SUM(d.HH_10K_TO_24K) AS HH_10K_TO_24K,
    SUM(d.HH_25K_TO_49K) AS HH_25K_TO_49K,
    SUM(d.HH_50K_TO_99K) AS HH_50K_TO_99K,
    SUM(d.HH_100K_TO_199K) AS HH_100K_TO_199K,
    SUM(d.HH_200K_PLUS) AS HH_200K_PLUS,
    ROUND(AVG(d.MEDIAN_HOUSEHOLD_INCOME), 0) AS AVG_MEDIAN_HOUSEHOLD_INCOME,
    ROUND(AVG(d.PER_CAPITA_INCOME), 0) AS AVG_PER_CAPITA_INCOME
FROM income_dist d
JOIN fips f ON d.STATE_FIPS = f.STATE_FIPS AND d.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 3. V_HOUSING: Housing by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_HOUSING AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
housing AS (
    SELECT
        LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS,
        SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B25001e1" AS TOTAL_HOUSING_UNITS,
        "B25003e2" AS OWNER_OCCUPIED,
        "B25003e3" AS RENTER_OCCUPIED,
        "B25077e1" AS MEDIAN_HOME_VALUE
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B25"
)
SELECT
    f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(h.TOTAL_HOUSING_UNITS) AS TOTAL_HOUSING_UNITS,
    SUM(h.OWNER_OCCUPIED) AS OWNER_OCCUPIED_UNITS,
    SUM(h.RENTER_OCCUPIED) AS RENTER_OCCUPIED_UNITS,
    ROUND(AVG(h.MEDIAN_HOME_VALUE), 0) AS AVG_MEDIAN_HOME_VALUE
FROM housing h
JOIN fips f ON h.STATE_FIPS = f.STATE_FIPS AND h.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 4. V_EDUCATION: Educational attainment by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_EDUCATION AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
edu AS (
    SELECT
        LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS,
        SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B15003e1" AS TOTAL_POP_25_PLUS,
        ("B15003e2"+"B15003e3"+"B15003e4"+"B15003e5"+"B15003e6"+"B15003e7"+"B15003e8"+"B15003e9"+"B15003e10"+"B15003e11"+"B15003e12"+"B15003e13"+"B15003e14"+"B15003e15"+"B15003e16") AS LESS_THAN_HIGH_SCHOOL,
        ("B15003e17"+"B15003e18") AS HIGH_SCHOOL_OR_GED,
        ("B15003e19"+"B15003e20") AS SOME_COLLEGE,
        "B15003e21" AS ASSOCIATES_DEGREE,
        "B15003e22" AS BACHELORS_DEGREE,
        "B15003e23" AS MASTERS_DEGREE,
        ("B15003e24"+"B15003e25") AS PROFESSIONAL_OR_DOCTORATE
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B15"
)
SELECT
    f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(e.TOTAL_POP_25_PLUS) AS TOTAL_POP_25_PLUS,
    SUM(e.LESS_THAN_HIGH_SCHOOL) AS LESS_THAN_HIGH_SCHOOL,
    SUM(e.HIGH_SCHOOL_OR_GED) AS HIGH_SCHOOL_OR_GED,
    SUM(e.SOME_COLLEGE) AS SOME_COLLEGE,
    SUM(e.ASSOCIATES_DEGREE) AS ASSOCIATES_DEGREE,
    SUM(e.BACHELORS_DEGREE) AS BACHELORS_DEGREE,
    SUM(e.MASTERS_DEGREE) AS MASTERS_DEGREE,
    SUM(e.PROFESSIONAL_OR_DOCTORATE) AS PROFESSIONAL_OR_DOCTORATE
FROM edu e
JOIN fips f ON e.STATE_FIPS = f.STATE_FIPS AND e.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 5. V_EMPLOYMENT: Labor force by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_EMPLOYMENT AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
emp AS (
    SELECT
        LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS,
        SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B23025e1" AS POP_16_PLUS,
        "B23025e2" AS IN_LABOR_FORCE,
        "B23025e4" AS EMPLOYED,
        "B23025e5" AS UNEMPLOYED,
        "B23025e6" AS ARMED_FORCES,
        "B23025e7" AS NOT_IN_LABOR_FORCE
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B23"
)
SELECT
    f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(e.POP_16_PLUS) AS POP_16_PLUS,
    SUM(e.IN_LABOR_FORCE) AS IN_LABOR_FORCE,
    SUM(e.EMPLOYED) AS EMPLOYED,
    SUM(e.UNEMPLOYED) AS UNEMPLOYED,
    SUM(e.ARMED_FORCES) AS ARMED_FORCES,
    SUM(e.NOT_IN_LABOR_FORCE) AS NOT_IN_LABOR_FORCE,
    ROUND(SUM(e.UNEMPLOYED) * 100.0 / NULLIF(SUM(e.IN_LABOR_FORCE), 0), 2) AS UNEMPLOYMENT_RATE,
    ROUND(SUM(e.IN_LABOR_FORCE) * 100.0 / NULLIF(SUM(e.POP_16_PLUS), 0), 2) AS LABOR_FORCE_PARTICIPATION_RATE
FROM emp e
JOIN fips f ON e.STATE_FIPS = f.STATE_FIPS AND e.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 6. V_COMMUTE: Transportation to work by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_COMMUTE AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
commute AS (
    SELECT LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS, SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B08301e1" AS TOTAL_WORKERS, "B08301e3" AS DROVE_ALONE, "B08301e4" AS CARPOOLED,
        "B08301e10" AS PUBLIC_TRANSIT, "B08301e18" AS BICYCLE, "B08301e19" AS WALKED, "B08301e21" AS WORKED_FROM_HOME
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B08"
)
SELECT f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(c.TOTAL_WORKERS) AS TOTAL_WORKERS, SUM(c.DROVE_ALONE) AS DROVE_ALONE,
    SUM(c.CARPOOLED) AS CARPOOLED, SUM(c.PUBLIC_TRANSIT) AS PUBLIC_TRANSIT,
    SUM(c.BICYCLE) AS BICYCLE, SUM(c.WALKED) AS WALKED, SUM(c.WORKED_FROM_HOME) AS WORKED_FROM_HOME
FROM commute c
JOIN fips f ON c.STATE_FIPS = f.STATE_FIPS AND c.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 7. V_POVERTY: Poverty status by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_POVERTY AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
pov AS (
    SELECT LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS, SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B17021e1" AS TOTAL_POP_POVERTY_DETERMINED, "B17021e2" AS BELOW_POVERTY_LEVEL, "B17021e19" AS AT_OR_ABOVE_POVERTY_LEVEL
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B17"
)
SELECT f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(p.TOTAL_POP_POVERTY_DETERMINED) AS TOTAL_POP_POVERTY_DETERMINED,
    SUM(p.BELOW_POVERTY_LEVEL) AS BELOW_POVERTY_LEVEL,
    SUM(p.AT_OR_ABOVE_POVERTY_LEVEL) AS AT_OR_ABOVE_POVERTY_LEVEL,
    ROUND(SUM(p.BELOW_POVERTY_LEVEL) * 100.0 / NULLIF(SUM(p.TOTAL_POP_POVERTY_DETERMINED), 0), 1) AS POVERTY_RATE
FROM pov p
JOIN fips f ON p.STATE_FIPS = f.STATE_FIPS AND p.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 8. V_HEALTH_INSURANCE: Coverage by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_HEALTH_INSURANCE AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
ins AS (
    SELECT LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS, SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B27010e1" AS TOTAL_POP,
        "B27010e17" AS UNINSURED_UNDER_19, "B27010e33" AS UNINSURED_19_TO_34,
        "B27010e50" AS UNINSURED_35_TO_64, "B27010e66" AS UNINSURED_65_PLUS
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B27"
)
SELECT f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(i.TOTAL_POP) AS TOTAL_POP,
    SUM(i.UNINSURED_UNDER_19)+SUM(i.UNINSURED_19_TO_34)+SUM(i.UNINSURED_35_TO_64)+SUM(i.UNINSURED_65_PLUS) AS TOTAL_UNINSURED,
    SUM(i.TOTAL_POP)-(SUM(i.UNINSURED_UNDER_19)+SUM(i.UNINSURED_19_TO_34)+SUM(i.UNINSURED_35_TO_64)+SUM(i.UNINSURED_65_PLUS)) AS TOTAL_INSURED,
    ROUND((SUM(i.UNINSURED_UNDER_19)+SUM(i.UNINSURED_19_TO_34)+SUM(i.UNINSURED_35_TO_64)+SUM(i.UNINSURED_65_PLUS)) * 100.0 / NULLIF(SUM(i.TOTAL_POP), 0), 1) AS UNINSURED_RATE
FROM ins i
JOIN fips f ON i.STATE_FIPS = f.STATE_FIPS AND i.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 9. V_INTERNET: Broadband access by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_INTERNET AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
net AS (
    SELECT LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS, SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B28002e1" AS TOTAL_HOUSEHOLDS, "B28002e2" AS WITH_INTERNET_SUBSCRIPTION,
        "B28002e12" AS INTERNET_NO_SUBSCRIPTION, "B28002e13" AS NO_INTERNET_ACCESS
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B28"
)
SELECT f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(n.TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS,
    SUM(n.WITH_INTERNET_SUBSCRIPTION) AS WITH_INTERNET_SUBSCRIPTION,
    SUM(n.INTERNET_NO_SUBSCRIPTION) AS INTERNET_NO_SUBSCRIPTION,
    SUM(n.NO_INTERNET_ACCESS) AS NO_INTERNET_ACCESS,
    ROUND(SUM(n.WITH_INTERNET_SUBSCRIPTION) * 100.0 / NULLIF(SUM(n.TOTAL_HOUSEHOLDS), 0), 1) AS INTERNET_SUBSCRIPTION_RATE,
    ROUND(SUM(n.NO_INTERNET_ACCESS) * 100.0 / NULLIF(SUM(n.TOTAL_HOUSEHOLDS), 0), 1) AS NO_INTERNET_RATE
FROM net n
JOIN fips f ON n.STATE_FIPS = f.STATE_FIPS AND n.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 10. V_LANGUAGE: Household language by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_LANGUAGE AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
lang AS (
    SELECT LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS, SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "C16002e1" AS TOTAL_HOUSEHOLDS, "C16002e2" AS ENGLISH_ONLY, "C16002e3" AS SPANISH,
        "C16002e6" AS OTHER_INDO_EUROPEAN, "C16002e9" AS ASIAN_PACIFIC_ISLAND, "C16002e12" AS OTHER_LANGUAGES
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_C16"
)
SELECT f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(l.TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS, SUM(l.ENGLISH_ONLY) AS ENGLISH_ONLY,
    SUM(l.SPANISH) AS SPANISH, SUM(l.OTHER_INDO_EUROPEAN) AS OTHER_INDO_EUROPEAN,
    SUM(l.ASIAN_PACIFIC_ISLAND) AS ASIAN_PACIFIC_ISLAND, SUM(l.OTHER_LANGUAGES) AS OTHER_LANGUAGES,
    ROUND(SUM(l.ENGLISH_ONLY) * 100.0 / NULLIF(SUM(l.TOTAL_HOUSEHOLDS), 0), 1) AS PCT_ENGLISH_ONLY
FROM lang l
JOIN fips f ON l.STATE_FIPS = f.STATE_FIPS AND l.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 11. V_HOUSEHOLD_TYPE: Family structure by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_HOUSEHOLD_TYPE AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
hh AS (
    SELECT LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS, SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B11001e1" AS TOTAL_HOUSEHOLDS, "B11001e2" AS FAMILY_HOUSEHOLDS,
        "B11001e3" AS MARRIED_COUPLE_FAMILY, "B11001e4" AS OTHER_FAMILY,
        "B11001e7" AS NONFAMILY_HOUSEHOLDS, "B11001e8" AS LIVING_ALONE
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B11"
)
SELECT f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(h.TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS, SUM(h.FAMILY_HOUSEHOLDS) AS FAMILY_HOUSEHOLDS,
    SUM(h.MARRIED_COUPLE_FAMILY) AS MARRIED_COUPLE_FAMILY, SUM(h.OTHER_FAMILY) AS OTHER_FAMILY,
    SUM(h.NONFAMILY_HOUSEHOLDS) AS NONFAMILY_HOUSEHOLDS, SUM(h.LIVING_ALONE) AS LIVING_ALONE
FROM hh h
JOIN fips f ON h.STATE_FIPS = f.STATE_FIPS AND h.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 12. V_VETERANS: Veteran status by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_VETERANS AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
vet AS (
    SELECT LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS, SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B21001e1" AS TOTAL_POP_18_PLUS, "B21001e2" AS VETERANS, "B21001e3" AS NONVETERANS
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B21"
)
SELECT f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(v.TOTAL_POP_18_PLUS) AS TOTAL_POP_18_PLUS, SUM(v.VETERANS) AS VETERANS,
    SUM(v.NONVETERANS) AS NONVETERANS,
    ROUND(SUM(v.VETERANS) * 100.0 / NULLIF(SUM(v.TOTAL_POP_18_PLUS), 0), 1) AS VETERAN_RATE
FROM vet v
JOIN fips f ON v.STATE_FIPS = f.STATE_FIPS AND v.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

------------------------------------------------------------
-- 13. V_SNAP: Food stamp receipt by county
------------------------------------------------------------
CREATE OR REPLACE VIEW V_SNAP AS
WITH fips AS (
    SELECT DISTINCT STATE, STATE_FIPS, COUNTY_FIPS, COUNTY
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_METADATA_CBG_FIPS_CODES"
    WHERE STATE IS NOT NULL
),
snap AS (
    SELECT LEFT(CENSUS_BLOCK_GROUP, 2) AS STATE_FIPS, SUBSTR(CENSUS_BLOCK_GROUP, 3, 3) AS COUNTY_FIPS,
        "B22010e1" AS TOTAL_HOUSEHOLDS, "B22010e2" AS RECEIVED_SNAP, "B22010e5" AS DID_NOT_RECEIVE_SNAP
    FROM US_OPEN_CENSUS_DATA_NEIGHBORHOOD_INSIGHTS_FREE_DATASET.PUBLIC."2020_CBG_B22"
)
SELECT f.STATE AS STATE_NAME, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS,
    SUM(s.TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS, SUM(s.RECEIVED_SNAP) AS RECEIVED_SNAP,
    SUM(s.DID_NOT_RECEIVE_SNAP) AS DID_NOT_RECEIVE_SNAP,
    ROUND(SUM(s.RECEIVED_SNAP) * 100.0 / NULLIF(SUM(s.TOTAL_HOUSEHOLDS), 0), 1) AS SNAP_RATE
FROM snap s
JOIN fips f ON s.STATE_FIPS = f.STATE_FIPS AND s.COUNTY_FIPS = f.COUNTY_FIPS
GROUP BY f.STATE, f.STATE_FIPS, f.COUNTY, f.COUNTY_FIPS;

-- ============================================================
-- STATE-LEVEL VIEWS (one row per state, pre-aggregated)
-- All include TOTAL_POPULATION for easy ORDER BY / filtering
-- ============================================================

------------------------------------------------------------
-- 14. V_STATE_SUMMARY: Population rollup
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_SUMMARY AS
SELECT STATE_NAME, STATE_FIPS,
    SUM(TOTAL_POPULATION) AS TOTAL_POPULATION, SUM(MALE_POPULATION) AS MALE_POPULATION,
    SUM(FEMALE_POPULATION) AS FEMALE_POPULATION, SUM(POP_UNDER_18) AS POP_UNDER_18,
    SUM(POP_18_TO_34) AS POP_18_TO_34, SUM(POP_35_TO_54) AS POP_35_TO_54,
    SUM(POP_55_TO_69) AS POP_55_TO_69, SUM(POP_70_PLUS) AS POP_70_PLUS,
    SUM(WHITE_NON_HISPANIC) AS WHITE_NON_HISPANIC, SUM(BLACK_NON_HISPANIC) AS BLACK_NON_HISPANIC,
    SUM(ASIAN_NON_HISPANIC) AS ASIAN_NON_HISPANIC, SUM(HISPANIC_LATINO) AS HISPANIC_LATINO
FROM V_POPULATION GROUP BY STATE_NAME, STATE_FIPS;

------------------------------------------------------------
-- 15. V_STATE_INCOME
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_INCOME AS
SELECT i.STATE_NAME, i.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(i.TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS, SUM(i.HH_UNDER_10K) AS HH_UNDER_10K,
    SUM(i.HH_10K_TO_24K) AS HH_10K_TO_24K, SUM(i.HH_25K_TO_49K) AS HH_25K_TO_49K,
    SUM(i.HH_50K_TO_99K) AS HH_50K_TO_99K, SUM(i.HH_100K_TO_199K) AS HH_100K_TO_199K,
    SUM(i.HH_200K_PLUS) AS HH_200K_PLUS,
    ROUND(AVG(NULLIF(i.AVG_MEDIAN_HOUSEHOLD_INCOME, 0)), 0) AS MEDIAN_HOUSEHOLD_INCOME,
    ROUND(AVG(NULLIF(i.AVG_PER_CAPITA_INCOME, 0)), 0) AS PER_CAPITA_INCOME
FROM V_INCOME i JOIN V_STATE_SUMMARY s ON i.STATE_NAME = s.STATE_NAME
GROUP BY i.STATE_NAME, i.STATE_FIPS, s.TOTAL_POPULATION;

------------------------------------------------------------
-- 16. V_STATE_EMPLOYMENT
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_EMPLOYMENT AS
SELECT e.STATE_NAME, e.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(e.POP_16_PLUS) AS POP_16_PLUS, SUM(e.IN_LABOR_FORCE) AS IN_LABOR_FORCE,
    SUM(e.EMPLOYED) AS EMPLOYED, SUM(e.UNEMPLOYED) AS UNEMPLOYED,
    SUM(e.ARMED_FORCES) AS ARMED_FORCES, SUM(e.NOT_IN_LABOR_FORCE) AS NOT_IN_LABOR_FORCE,
    ROUND(SUM(e.UNEMPLOYED) * 100.0 / NULLIF(SUM(e.IN_LABOR_FORCE), 0), 2) AS UNEMPLOYMENT_RATE,
    ROUND(SUM(e.IN_LABOR_FORCE) * 100.0 / NULLIF(SUM(e.POP_16_PLUS), 0), 2) AS LABOR_FORCE_PARTICIPATION_RATE
FROM V_EMPLOYMENT e JOIN V_STATE_SUMMARY s ON e.STATE_NAME = s.STATE_NAME
GROUP BY e.STATE_NAME, e.STATE_FIPS, s.TOTAL_POPULATION;

------------------------------------------------------------
-- 17. V_STATE_EDUCATION
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_EDUCATION AS
SELECT ed.STATE_NAME, ed.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(ed.TOTAL_POP_25_PLUS) AS TOTAL_POP_25_PLUS, SUM(ed.LESS_THAN_HIGH_SCHOOL) AS LESS_THAN_HIGH_SCHOOL,
    SUM(ed.HIGH_SCHOOL_OR_GED) AS HIGH_SCHOOL_OR_GED, SUM(ed.SOME_COLLEGE) AS SOME_COLLEGE,
    SUM(ed.ASSOCIATES_DEGREE) AS ASSOCIATES_DEGREE, SUM(ed.BACHELORS_DEGREE) AS BACHELORS_DEGREE,
    SUM(ed.MASTERS_DEGREE) AS MASTERS_DEGREE, SUM(ed.PROFESSIONAL_OR_DOCTORATE) AS PROFESSIONAL_OR_DOCTORATE,
    ROUND(SUM(ed.BACHELORS_DEGREE) * 100.0 / NULLIF(SUM(ed.TOTAL_POP_25_PLUS), 0), 1) AS PCT_BACHELORS,
    ROUND((SUM(ed.BACHELORS_DEGREE)+SUM(ed.MASTERS_DEGREE)+SUM(ed.PROFESSIONAL_OR_DOCTORATE)) * 100.0 / NULLIF(SUM(ed.TOTAL_POP_25_PLUS), 0), 1) AS PCT_COLLEGE_OR_HIGHER
FROM V_EDUCATION ed JOIN V_STATE_SUMMARY s ON ed.STATE_NAME = s.STATE_NAME
GROUP BY ed.STATE_NAME, ed.STATE_FIPS, s.TOTAL_POPULATION;

------------------------------------------------------------
-- 18. V_STATE_HOUSING
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_HOUSING AS
SELECT h.STATE_NAME, h.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(h.TOTAL_HOUSING_UNITS) AS TOTAL_HOUSING_UNITS, SUM(h.OWNER_OCCUPIED_UNITS) AS OWNER_OCCUPIED_UNITS,
    SUM(h.RENTER_OCCUPIED_UNITS) AS RENTER_OCCUPIED_UNITS,
    ROUND(SUM(h.OWNER_OCCUPIED_UNITS) * 100.0 / NULLIF(SUM(h.OWNER_OCCUPIED_UNITS)+SUM(h.RENTER_OCCUPIED_UNITS), 0), 1) AS HOMEOWNERSHIP_RATE,
    ROUND(AVG(NULLIF(h.AVG_MEDIAN_HOME_VALUE, 0)), 0) AS MEDIAN_HOME_VALUE
FROM V_HOUSING h JOIN V_STATE_SUMMARY s ON h.STATE_NAME = s.STATE_NAME
GROUP BY h.STATE_NAME, h.STATE_FIPS, s.TOTAL_POPULATION;

------------------------------------------------------------
-- 19. V_STATE_COMMUTE
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_COMMUTE AS
SELECT c.STATE_NAME, c.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(c.TOTAL_WORKERS) AS TOTAL_WORKERS, SUM(c.DROVE_ALONE) AS DROVE_ALONE,
    SUM(c.CARPOOLED) AS CARPOOLED, SUM(c.PUBLIC_TRANSIT) AS PUBLIC_TRANSIT,
    SUM(c.BICYCLE) AS BICYCLE, SUM(c.WALKED) AS WALKED, SUM(c.WORKED_FROM_HOME) AS WORKED_FROM_HOME,
    ROUND(SUM(c.DROVE_ALONE) * 100.0 / NULLIF(SUM(c.TOTAL_WORKERS), 0), 1) AS PCT_DROVE_ALONE,
    ROUND(SUM(c.PUBLIC_TRANSIT) * 100.0 / NULLIF(SUM(c.TOTAL_WORKERS), 0), 1) AS PCT_PUBLIC_TRANSIT,
    ROUND(SUM(c.WORKED_FROM_HOME) * 100.0 / NULLIF(SUM(c.TOTAL_WORKERS), 0), 1) AS PCT_WORK_FROM_HOME
FROM V_COMMUTE c JOIN V_STATE_SUMMARY s ON c.STATE_NAME = s.STATE_NAME
GROUP BY c.STATE_NAME, c.STATE_FIPS, s.TOTAL_POPULATION;

------------------------------------------------------------
-- 20. V_STATE_POVERTY
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_POVERTY AS
SELECT p.STATE_NAME, p.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(p.TOTAL_POP_POVERTY_DETERMINED) AS TOTAL_POP_POVERTY_DETERMINED,
    SUM(p.BELOW_POVERTY_LEVEL) AS BELOW_POVERTY_LEVEL,
    SUM(p.AT_OR_ABOVE_POVERTY_LEVEL) AS AT_OR_ABOVE_POVERTY_LEVEL,
    ROUND(SUM(p.BELOW_POVERTY_LEVEL) * 100.0 / NULLIF(SUM(p.TOTAL_POP_POVERTY_DETERMINED), 0), 1) AS POVERTY_RATE
FROM V_POVERTY p JOIN V_STATE_SUMMARY s ON p.STATE_NAME = s.STATE_NAME
GROUP BY p.STATE_NAME, p.STATE_FIPS, s.TOTAL_POPULATION;

------------------------------------------------------------
-- 21. V_STATE_HEALTH_INSURANCE
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_HEALTH_INSURANCE AS
SELECT h.STATE_NAME, h.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(h.TOTAL_POP) AS TOTAL_POP, SUM(h.TOTAL_UNINSURED) AS TOTAL_UNINSURED,
    SUM(h.TOTAL_INSURED) AS TOTAL_INSURED,
    ROUND(SUM(h.TOTAL_UNINSURED) * 100.0 / NULLIF(SUM(h.TOTAL_POP), 0), 1) AS UNINSURED_RATE
FROM V_HEALTH_INSURANCE h JOIN V_STATE_SUMMARY s ON h.STATE_NAME = s.STATE_NAME
GROUP BY h.STATE_NAME, h.STATE_FIPS, s.TOTAL_POPULATION;

------------------------------------------------------------
-- 22. V_STATE_INTERNET
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_INTERNET AS
SELECT n.STATE_NAME, n.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(n.TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS, SUM(n.WITH_INTERNET_SUBSCRIPTION) AS WITH_INTERNET_SUBSCRIPTION,
    SUM(n.NO_INTERNET_ACCESS) AS NO_INTERNET_ACCESS,
    ROUND(SUM(n.WITH_INTERNET_SUBSCRIPTION) * 100.0 / NULLIF(SUM(n.TOTAL_HOUSEHOLDS), 0), 1) AS INTERNET_SUBSCRIPTION_RATE,
    ROUND(SUM(n.NO_INTERNET_ACCESS) * 100.0 / NULLIF(SUM(n.TOTAL_HOUSEHOLDS), 0), 1) AS NO_INTERNET_RATE
FROM V_INTERNET n JOIN V_STATE_SUMMARY s ON n.STATE_NAME = s.STATE_NAME
GROUP BY n.STATE_NAME, n.STATE_FIPS, s.TOTAL_POPULATION;

------------------------------------------------------------
-- 23. V_STATE_LANGUAGE
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_LANGUAGE AS
SELECT l.STATE_NAME, l.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(l.TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS, SUM(l.ENGLISH_ONLY) AS ENGLISH_ONLY,
    SUM(l.SPANISH) AS SPANISH, SUM(l.OTHER_INDO_EUROPEAN) AS OTHER_INDO_EUROPEAN,
    SUM(l.ASIAN_PACIFIC_ISLAND) AS ASIAN_PACIFIC_ISLAND, SUM(l.OTHER_LANGUAGES) AS OTHER_LANGUAGES,
    ROUND(SUM(l.ENGLISH_ONLY) * 100.0 / NULLIF(SUM(l.TOTAL_HOUSEHOLDS), 0), 1) AS PCT_ENGLISH_ONLY,
    ROUND(SUM(l.SPANISH) * 100.0 / NULLIF(SUM(l.TOTAL_HOUSEHOLDS), 0), 1) AS PCT_SPANISH
FROM V_LANGUAGE l JOIN V_STATE_SUMMARY s ON l.STATE_NAME = s.STATE_NAME
GROUP BY l.STATE_NAME, l.STATE_FIPS, s.TOTAL_POPULATION;

------------------------------------------------------------
-- 24. V_STATE_HOUSEHOLD_TYPE
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_HOUSEHOLD_TYPE AS
SELECT h.STATE_NAME, h.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(h.TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS, SUM(h.FAMILY_HOUSEHOLDS) AS FAMILY_HOUSEHOLDS,
    SUM(h.MARRIED_COUPLE_FAMILY) AS MARRIED_COUPLE_FAMILY, SUM(h.OTHER_FAMILY) AS OTHER_FAMILY,
    SUM(h.NONFAMILY_HOUSEHOLDS) AS NONFAMILY_HOUSEHOLDS, SUM(h.LIVING_ALONE) AS LIVING_ALONE,
    ROUND(SUM(h.FAMILY_HOUSEHOLDS) * 100.0 / NULLIF(SUM(h.TOTAL_HOUSEHOLDS), 0), 1) AS PCT_FAMILY_HOUSEHOLDS,
    ROUND(SUM(h.LIVING_ALONE) * 100.0 / NULLIF(SUM(h.TOTAL_HOUSEHOLDS), 0), 1) AS PCT_LIVING_ALONE
FROM V_HOUSEHOLD_TYPE h JOIN V_STATE_SUMMARY s ON h.STATE_NAME = s.STATE_NAME
GROUP BY h.STATE_NAME, h.STATE_FIPS, s.TOTAL_POPULATION;

------------------------------------------------------------
-- 25. V_STATE_VETERANS
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_VETERANS AS
SELECT v.STATE_NAME, v.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(v.TOTAL_POP_18_PLUS) AS TOTAL_POP_18_PLUS, SUM(v.VETERANS) AS VETERANS,
    SUM(v.NONVETERANS) AS NONVETERANS,
    ROUND(SUM(v.VETERANS) * 100.0 / NULLIF(SUM(v.TOTAL_POP_18_PLUS), 0), 1) AS VETERAN_RATE
FROM V_VETERANS v JOIN V_STATE_SUMMARY s ON v.STATE_NAME = s.STATE_NAME
GROUP BY v.STATE_NAME, v.STATE_FIPS, s.TOTAL_POPULATION;

------------------------------------------------------------
-- 26. V_STATE_SNAP
------------------------------------------------------------
CREATE OR REPLACE VIEW V_STATE_SNAP AS
SELECT sn.STATE_NAME, sn.STATE_FIPS, s.TOTAL_POPULATION,
    SUM(sn.TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS, SUM(sn.RECEIVED_SNAP) AS RECEIVED_SNAP,
    SUM(sn.DID_NOT_RECEIVE_SNAP) AS DID_NOT_RECEIVE_SNAP,
    ROUND(SUM(sn.RECEIVED_SNAP) * 100.0 / NULLIF(SUM(sn.TOTAL_HOUSEHOLDS), 0), 1) AS SNAP_RATE
FROM V_SNAP sn JOIN V_STATE_SUMMARY s ON sn.STATE_NAME = s.STATE_NAME
GROUP BY sn.STATE_NAME, sn.STATE_FIPS, s.TOTAL_POPULATION;
